export const GET_COUNTRY_DATA_SUCCESS = 'GET_COUNTRY_DATA_SUCCESS';
export const GET_COUNTRY_DATA_ERROR = 'GET_COUNTRY_DATA_ERROR';

export const GET_WEATHER_DATA_SUCCESS = 'GET_WEATHER_DATA_SUCCESS';
export const GET_WEATHER_DATA_ERROR = 'GET_WEATHER_DATA_ERROR';

export const CLEAR_DATA = 'CLEAR_DATA';